# Generated by Django 3.2 on 2022-02-24 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onbeats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
    ]
