# Generated by Django 3.2 on 2022-03-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onbeats', '0002_remove_song_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
