# Generated by Django 3.2 on 2022-03-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onbeats', '0004_auto_20220303_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(max_length=255, unique_for_year=models.DateTimeField(auto_now_add=True)),
        ),
    ]
