# Generated by Django 3.2 on 2022-03-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onbeats', '0005_alter_album_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(max_length=255, unique_for_date=models.DateTimeField(auto_now_add=True)),
        ),
    ]
