# Generated by Django 3.2 on 2022-05-18 08:10

import django.core.validators
from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('onbeats', '0009_alter_song_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(max_length=5000, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='albums_cover/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='cover',
            field=models.ImageField(max_length=5000, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='artists_cover/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='profile',
            field=models.ImageField(max_length=5000, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='artists_profile/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(help_text='Allowed .mp3 files', storage=gdstorage.storage.GoogleDriveStorage(), upload_to='songs_file/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])]),
        ),
    ]
